language: objective-c
osx_image: mavericks
notifications:
  email: false
branches:
  only:
    - master
before_script:
  - git clone https://github.com/visionmedia/n.git /tmp/n 
  - bash -c 'cd /tmp/n && make install' 
  - npm install -g jshint grunt-cli
  - npm install
script:  
  - make travis
